V2G-liberty/addon-v2g-liberty

- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
You had already updated the host url, but to avoid any confusion, I also updated the url in commented-out lines.
> Finish updating FlexMeasures host url

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/appdaemon.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/flexmeasures_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/modbus_evse_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_liberty.py
json.load instead of json.loads
Some minor other bugs fixed
> FIXED BUG #25: Settings get lost

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/flexmeasures_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_globals.py
Also (temporarily) removed ping to flexmeasures.
> #28 BUG: Reset to factory defaults is broken.

- CHANGELOG.md
- v2g-liberty/DOCS.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/reservations_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/v2g-liberty/homeassistant/packages/v2g_liberty/v2g_liberty_dashboard.yaml
Temp. fix whereby only one local calendar is supported and the input select is removed..
> #27 Local calendar not working. 

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/flexmeasures_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/reservations_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_liberty.py
- v2g-liberty/rootfs/root/v2g-liberty/homeassistant/packages/v2g_liberty/v2g_liberty_dashboard.yaml
The temporary removal of the calendar select of version 1.7 has been reversed.
Try - Except added for calling other modules to increase stability
> Bug fix #32 Local calendar only works if one calendar is present.

- CHANGELOG.md
- v2g-liberty/DOCS.md
- v2g-liberty/config.yaml
- v2g-liberty/requirements.txt
- v2g-liberty/rootfs/etc/s6-overlay/s6-rc.d/init-appdaemon/run
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/apps.yaml
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/fm_client.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/get_fm_data.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/set_fm_data.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/v2g-liberty/appdaemon/apps/v2g-liberty/v2g_liberty.py
- v2g-liberty/rootfs/root/v2g-liberty/homeassistant/packages/v2g_liberty/v2g_liberty_dashboard.yaml
- v2g-liberty/rootfs/root/v2g-liberty/homeassistant/packages/v2g_liberty/v2g_liberty_package.yaml
Also:
- Introduced flexmeasures_client python library for stability and reduction of code complexity.
- Minor improvements in documentation.
- Made setting options in a select more robust
- Temporary remover the option "self_provided" for energy prices as users for this functionality use another repository.
> Bug fix #34 Getting sensor_id's from FM instead of through UI

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/modbus_evse_client.py
- Just opening the connection, not closing anymore. Only when configuration changes.
- Removed function to always have one call open at a time as well.
- Reverting to defaults for modbus client timeout, retries, reconnect_delay and _max.
> #48 Modbus possibly more stable when not closing connection after every call.

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/get_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/v2g_liberty_dashboard.yaml
> Problems with getting data, async issues.

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/reservations_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
- Bug #57: Calendar can now handle all-day events.
- Bug (Unnumbered): Better handle empty calendar
- Bug (unnumbered): More robust cancel_listener
> Bug fix release

- CHANGELOG.md
- v2g-liberty/Dockerfile
- v2g-liberty/build.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/apps.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/amber_price_data_manager.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/constants.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/get_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/octopus_price_data_manager.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/set_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/v2g_liberty_dashboard.yaml
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/v2g_liberty_package.yaml
Including a bug-fix for build versions of the AppDaemon add-on.
> 59 add support for octopus energy contracts

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/modbus_evse_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/set_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
- Init now always kicks off first soc and power readings.
- Introduced async.
- Renamed private methods
Removed log statement from modbus_client as it resulted in too many entries in the log.
> #63 BUG in set_fm_data getting data from V2G Liberty.

- README.md
- v2g-liberty/DOCS.md
- v2g-liberty/config.yaml
With some alterations/improvements on the documentation.
> #69 Version 0.2.0 release 

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
- Made methods involved in canceling timers sync (again).
> #74 🪲 BUG: Too frequent fluctuating (scheduled) charge power

- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/modbus_evse_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
Also set version to 0.2.1 as this is to be merged into the release branch for that version.
> #74 🪲 BUG: soc does not get renewed when car gets connected

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
Addendum, SoC prognosis line of schedule was never shown (deleted right after being created), that is fixed now.
> #81 Add "expected SoC" when "Max charge now" is activated

- CHANGELOG.md
- v2g-liberty/config.yaml
- Changed version number (in config yaml) to 0.3.0 (instead of 0.2.1) to comply with semantic versioning, new features where added.
- Completed CHANGELOG.md
> #87 Last changes before release

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/get_fm_data.py
For BUG #92: Price and emission data for tomorrow does not get loaded/shown
> 🩹 PATCH release 0.3.1

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/modbus_evse_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/octopus_price_data_manager.py
As this is relevant to specifically one user i decided not to make a new version in config.yaml
- Fixed wrong name self.second_try_time_get_data for octopus_price_data_manager.py
- Removed blocking set_charge_power in modbus_evse_client.py as this blocks try_get_soc.
> PATCH for minor bugs in octopus_price_data_manager and modbus_evse_client

- CHANGELOG.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_liberty.py
- This makes recovering from invalid SoC more robust
- BUMP own version to 0.3.2
>  #108 REFACTOR: Restructure code in set_next_action

- v2g-liberty/rootfs/root/appdaemon/apps/v2g-liberty/v2g_globals.py
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/v2g_liberty_package.yaml
Also changed upper limit for max-charge from 100(%) to 95 as the Leaf will never charge above 97% via CHAdeMo.
>  #113  TECH: Add "initialised" attribute to settings entities (=preparation for UI improvements)

- .gitignore
- v2g-liberty/.vscode/launch.json
- v2g-liberty/.vscode/tasks.json
- v2g-liberty/pytest.ini
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/settings_manager.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_globals.py
- v2g-liberty/rootfs/root/appdaemon/tests/test_settings_manager.py
I have refactored the retrieving and storing of the settings into a separate module and added unit tests for them.
> Refactor: SettingsManager + unit test

- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/get_fm_data.py
Added only for the prices as emissions have a 5 min. resolution and are already added to 23:55.
>  #148 🪲 BUG: Chart lines for prices / emissions do not extend to the period they represent.

- v2g-liberty/rootfs/etc/s6-overlay/s6-rc.d/init-appdaemon/run
This fixes the problems with updating the chart.
> Hot-fix for failing chart update

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/get_fm_data.py
- Fixed problem
- Also fixed situation where consumption and production prices are different.
- Cleanup of code
>  #169 🪲 BUG: Alert for negative prices not working correctly

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/config.yaml
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/amber_price_data_manager.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/get_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/octopus_price_data_manager.py
- Fixed unit_of_measure problem for Amber
- Made fix for both Amber and Octopus that was introduced by refactoring for version 0.4.0.
> #173 🪲 BUG-FIX release 0.4.2: Amber price data does not get sent

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/v2g_liberty_ui_module_stats.yaml
Added "Loading..." to card content while relevant entities have no value.
> 181 bug cost data blinking at startup

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/get_fm_data.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/modbus_evse_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_globals.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_liberty.py
- input_text instead of sensor entities for chart lines
- disconnect detection not correct
- writing None values to sensors leads to HA errors
> #196 HOTFIX problems:

- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/modbus_evse_client.py
As the charger will return 0 for the SoC while the car is not connected the initialisation should be able to handle this correctly. Now it returns a best guess: the minimum acceptable value, 2%, but this is not correct.
Removed use of "best guess" for read values that are out of range, when the current value is None (at startup).
Replaced by "unavailable" in this case.
Widened the acceptable value to the relaxed range if this is applicable (soc).
> #200 Restart while not connected

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/requirements.txt
Tested on test environment with mock charger, will test on real charger.
> Bumped pymodbus to 3.8.3. 

- .devcontainer/docker-compose.yaml
- .gitignore
Removed redundant comment from .gitignore
> Changed docker-compose.yaml.

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_liberty.py
- v2g-liberty/rootfs/root/homeassistant/packages/v2g_liberty/main_view.yaml
Removed separate cards for alerts, combined with card for optimisation mode/electricity provider.
> Fixed layout and texts.

- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/constants.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/fm_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_globals.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_liberty.py
- Added set_version and __set_attribute to fm_client
- Added constant FM_ASSET_NAME, written by globals.
- Added (delayed) call to new method log_version to v2g_liberty
> Added feature to send version to fm

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/fm_client.py
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/v2g_globals.py
Added `relax-soc-constraints` and `relax-capacity-constraints` to `flex_context`.
> Removed "altered soc_minima" for 1st calendar_event.

- v2g-liberty/CHANGELOG.md
- v2g-liberty/changelog_of_all_releases.md
- v2g-liberty/rootfs/root/appdaemon/apps/v2g_liberty/main_app.py
- Added an extra 0-value before the calenadar item in the `__draw_event_in_graph()` method in the `main_app.py`.
- Removed the timedelta + 1 from the extra 0-value after the ci
> Changed the values that are written into the ha-entity `calender_item_in_chart`
